name: gen_err_sel_ssm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - matplotlib
  - scikit-learn
  - einops
  - ipykernel
  - pip
  - pip:
      - torchmetrics
      - transformers
      - datasets
